name = "vibecodr-web"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "apps/web/dist"


[vars]
NEXT_PUBLIC_BASE_URL = "https://vibecodr.space"
NEXT_PUBLIC_RUNTIME_BUNDLE_NETWORK_MODE = "offline"
